apiVersion: v1
kind: Service
metadata:
  labels:
    app: company-api
    env: aks
  name: company-api
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: company-api
  type: LoadBalancer
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: company-api
    env: aks
  name: company-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: company-api
  template:
    metadata:
      labels:
        app: company-api
    spec:
      containers:
      - env:
        - name: SPRING_PROFILES_ACTIVE
          value: minikube
        - name: MONGODB_HOST
          value: mongo-0
        image: myprivatereg.azurecr.io/company-api:1.0
        imagePullPolicy: IfNotPresent
        name: company-api
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 90
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 90