apiVersion: v1
kind: Service
metadata:
  labels:
    app: employee-api
    env: aks
  name: employee-api
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: employee-api
  type: LoadBalancer
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: employee-api
    env: aks
  name: employee-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employee-api
  template:
    metadata:
      labels:
        app: employee-api
    spec:
      containers:
      - env:
        - name: MONGODB_HOST
          value: mongo-0
        image: myprivatereg.azurecr.io/employee-api:1.0
        imagePullPolicy: IfNotPresent
        name: employee-api
        ports:
        - containerPort: 8000
        livenessProbe:
          httpGet:
            path: /meta/health
            port: 8000
        readinessProbe:
          httpGet:
            path: /meta/health
            port: 8000