apiVersion: v1
kind: Pod
metadata:
  name: company-api
  labels:
    env: localkube
    app: company-api
spec:
  containers:
  - name: company-api
    image: company-api:1.0.0
    env:
    - name: SPRING_PROFILES_ACTIVE
      value: minikube
    - name: MONGODB_HOST
      value: mongo
    ports:
    - containerPort: 8080