version: '2'
services: 
  app:
    build: .
    container_name: employee-api
    ports: 
      - "8000:8000"
    depends_on: 
      - mongo
    restart: always
    environment: 
      - MONGODB_HOST=mongo
  mongo:
    image: mongo:3.6
    hostname: mongo
    ports: 
      - "27017:27017"
    restart: always