apiVersion: v1
kind: Pod
metadata:
  name: mongo
  labels:
    env: localkube
    app: mongo
spec:
  containers:
  - name: mongo
    image: mongo:3.6
    ports:
    - containerPort: 27017
    volumeMounts:
    - name: mongo-data
      mountPath: /data/db
  volumes:
  - name: mongo-data
    persistentVolumeClaim:
      claimName: mongo-pv-claim