apiVersion: v1
kind: Pod
metadata:
  name: frontend
  labels:
    env: localkube
    app: frontend
spec:
  containers:
  - name: frontend
    image: frontend:1.0.0
    env:
    - name: PORT
      value: "3000"
    - name: REACT_APP_EMPLOYEE_API
      value: "(EMPLOYEEAPI ENDPOINT)"
    - name: REACT_APP_COMPANY_API
      value: "(COMPANYAPI ENDPOINT)"
    ports:
    - containerPort: 3000